# automatically fetch contract sources from Etherscan
autofetch_sources: True

reports:

networks:
  default: mainnet-fork
  development:
    cmd_settings:
      unlock: 
        - 0xC5aF91F7D10dDe118992ecf536Ed227f276EC60D

compiler:
  solc:
    version: 0.8.13
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
      - '@oz-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.2'
      - '@yearn-vaults=yearn/yearn-vaults@0.4.3'
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.2
  - yearn/yearn-vaults@0.4.3